# Basic values.yaml configuration for Kong for Kubernetes (with the ingress controller)

image:
  repository: kong
  # tag: "3.5"

env:
  prefix: /kong_prefix/
  database: "off"

manager:
  enabled: false

ingressController:
  enabled: true

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - upstream
            - k6
        topologyKey: topology.kubernetes.io/zone