auth:
  password: redispassword1

master:
  persistence:
    storageClass: gp2
  nodeSelector:
    benchmark.konghq.com/node-role: support
  tolerations:
    - key: dedicated
      operator: Equal
      value: support
      effect: NoSchedule
