# Basic values.yaml configuration for Kong for Kubernetes (with the ingress controller)

image:
  repository: kong

env:
  prefix: /kong_prefix/
  database: "off"
  # TODO: set this based on node cores
  nginx_worker_processes: 32

proxy:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8100"

manager:
  enabled: false

admin:
  enabled: false

ingressController:
  enabled: true

tolerations:
  - key: "dedicated"
    value: "kong"
    effect: "NoSchedule"